/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.themaddungeon.Vista;

import java.awt.event.ActionListener;

/**
 *
 * @author esteb
 */
public class GUIInstrucciones extends javax.swing.JFrame {

    /**
     * Creates new form GUIInstrucciones
     */
    public GUIInstrucciones() {
        initComponents();
        
    }
    
    public void escuchar(ActionListener controlador){
        
        btnatras.addActionListener(controlador);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnatras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vacioParaBoton.png"))); // NOI18N
        btnatras.setActionCommand("btnatras");
        btnatras.setBorderPainted(false);
        btnatras.setContentAreaFilled(false);
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 170, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Instrucciones del juego REDIMENSIONADAS.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnatrasActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatras;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
