/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.themaddungeon.Vista;

import com.mycompany.themaddungeon.Conatrolador.ControladorPrincipal;
import java.awt.event.ActionListener;

/**
 *
 * @author esteb
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    } 
    
    
    public void escuchar(ControladorPrincipal controlador){
        btnInstrucciones.addActionListener((ActionListener) controlador);
        btnJugar.addActionListener((ActionListener) controlador);
        btnSalir.addActionListener((ActionListener) controlador);
        btnHistoria.addActionListener((ActionListener) controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vacioParaBoton.png"))); // NOI18N
        btnJugar.setActionCommand("jugar");
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 120, 50));

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vacioParaBoton.png"))); // NOI18N
        btnInstrucciones.setActionCommand("instrucciones");
        btnInstrucciones.setBorderPainted(false);
        btnInstrucciones.setContentAreaFilled(false);
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 160, 60));

        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vacioParaBoton.png"))); // NOI18N
        btnHistoria.setActionCommand("historia");
        btnHistoria.setBorderPainted(false);
        btnHistoria.setContentAreaFilled(false);
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 120, 60));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vacioParaBoton.png"))); // NOI18N
        btnSalir.setActionCommand("salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portada del juego REDIMENSIONADA.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
